### ISSUE TITLE
php70 failed to build on 10.5.8

### ISSUE THREAD

**Issue by bryancn** [mistydemeo/tigerbrew#432]
Error: undefined method `rebuild' for #<BottleSpecification:0x1296688>
https://gist.github.com/bryancn/bb43f498a59c9994c8c42efbcaa24f51

No log files, but other info in the gist
PHP56 fails with an identical:
Error: undefined method `rebuild' for #<BottleSpecification:0x1296688>
So I presume I've set something up wrong.
Machine previously has Macports on it but deinstall was routine.

**Comment by mistydemeo** [comment]
I haven't updated Tigerbrew's core code in awhile; the PHP tap is using newer features that Tigerbrew doesn't have access to.

Sometime over the next month or two, I'm aiming to bring Tigerbrew back up to date, at which point this will be fixed. Sorry for the inconvenience. :(

**Comment by bryancn** [comment]
Thanks for the update. I’ll look forward to it.

Great project! It’s made me enthusiastic about my G5 again…

B

**Comment by bryancn** [comment]
Seems to have been identified and fixed here https://github.com/Homebrew/homebrew-php/pull/3542 and here https://github.com/Homebrew/homebrew-core/issues/4204
