### ISSUE TITLE
tor.rb failed to build on  10.5.8(ppc/G4) dl-links dead, new tor requires openssl@1.1

### ISSUE THREAD

**Issue by yasuoiwakura** [mistydemeo/tigerbrew#675]
hi there,

tried to install tor.rb today, but the old sources are gone, plus tor needs an actual version to run.

new tor versions need openssl1.1 wich is not available in tigerbrew yet afaik.
i gave it a try to build openssl@1.1 directly but 

> 
>  ~> brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/master/Formula/openssl%401.1.rb
> ###################################################################################################################################################################################################################################### 100.0%
> Error: undefined method `version_scheme' for #<Class:0xffe3f8>
> Please report this bug:
>     https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
> /Users/matmin/Library/Caches/Homebrew/Formula/openssl%401.1.rb:8:in `<class:OpensslAT11>'
> /Users/matmin/Library/Caches/Homebrew/Formula/openssl%401.1.rb:1:in `load_formula'
> /usr/local/Library/Homebrew/formulary.rb:23:in `module_eval'
> /usr/local/Library/Homebrew/formulary.rb:23:in `load_formula'
> /usr/local/Library/Homebrew/formulary.rb:36:in `load_formula_from_path'
> /usr/local/Library/Homebrew/formulary.rb:86:in `load_file'
> /usr/local/Library/Homebrew/formulary.rb:141:in `load_file'
> /usr/local/Library/Homebrew/formulary.rb:77:in `klass'
> /usr/local/Library/Homebrew/formulary.rb:73:in `get_formula'
> /usr/local/Library/Homebrew/formulary.rb:208:in `factory'
> /usr/local/Library/Homebrew/extend/ARGV.rb:18:in `block in formulae'
> /usr/local/Library/Homebrew/extend/ARGV.rb:16:in `map'
> /usr/local/Library/Homebrew/extend/ARGV.rb:16:in `formulae'
> /usr/local/Library/Homebrew/cmd/install.rb:45:in `install'
> /usr/local/Library/brew.rb:143:in `<main>'
> 

https://gist.github.com/yasuoiwakura/5d7b3b180a48ba3d19d0d696a2439056#file-matt4g-doctor

**Comment by sevan** [comment]
If you obtain the latest version of the Tigerbrew repo and try the update in PR #820, that should give you v0.4.7.13 which is 1 version behind (latest is 0.4.7.14)

**Comment by sevan** [comment]
A more recent version of Tor which built on Tiger landed some time ago. Thanks for the report.
