### ISSUE TITLE
QEMU failed to build on 10.5.8

### ISSUE THREAD

**Issue by jschissel82** [mistydemeo/tigerbrew#489]
Getting error:

`ui/cocoa.m:913:55: error: 'filetypes' undeclared (first use in this function)`
`         [op beginSheetForDirectory:nil file:nil types:filetypes`

I've included the requested information in gist here:
[QEMU failed to build on 10.5.8](https://gist.github.com/jschissel82/41071ab9b4d5d751cb36bf5e52d3760b)

Brew doctor notice regarding X11 version is confusing because I have the updated version installed and it is operational as far as I can tell.  Had to use --cc=gcc-5 because the Apple version was failing with TLS error.

Maybe I'm doing something wrong?

**Comment by mistydemeo** [comment]
The code in question is this:

```objc
#if (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_6)
        [op setAllowedFileTypes:supportedImageFileTypes];
        [op beginSheetModalForWindow:normalWindow
            completionHandler:^(NSInteger returnCode)
            { [self openPanelDidEnd:op
                  returnCode:returnCode contextInfo:NULL ]; } ];
#else
        // Compatibility code for pre-10.6, using deprecated method
        [op beginSheetForDirectory:nil file:nil types:filetypes
              modalForWindow:normalWindow modalDelegate:self
              didEndSelector:@selector(openPanelDidEnd:returnCode:contextInfo:) contextInfo:NULL];
#endif
```

It looks like there's a bug in the pre-10.6 branch of the `#ifdef`; the variable it's accessing is named something different and used under that name in the first branch. Probably went unnoticed because not many people use qemu on 10.5.

The code in question was actually deleted upstream; the file dialogue was removed. At least that makes fixing it pretty easy!

**Comment by mistydemeo** [comment]
Should be fixed now!

**Comment by jschissel82** [comment]
Success, thank you!
