### ISSUE TITLE
openssl fail to build on 10.4 (G3)

### ISSUE THREAD

**Issue by boudinfl** [mistydemeo/tigerbrew#408]
openssl fail to build on my ibook g3 running osx tiger.

Below is the error message:

~ florian$ brew install curl
==> Installing dependencies for curl: openssl
==> Installing curl dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2d.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2d.tar.gz
/usr/bin/tar: A lone zero block at 52140
==> Downloading https://trac.macports.org/export/144472/trunk/dports/devel/openssl/files/x86_64-asm-on-i386.patch
Already downloaded: /Library/Caches/Homebrew/openssl--patch-98ffb308aa04c14db9c21769f1c5ff09d63eb85ce9afdf002598823c45edef6d.patch
==> Patching
Error: undefined method `count' for #<Array:0x609128>
Please report this bug:
    https://github.com/mistydemeo/tigerbrew/wiki/troubleshooting
/usr/local/Library/Homebrew/patch.rb:133:in `apply'
/usr/local/Library/Homebrew/patch.rb:129:in `unpack'
/usr/local/Library/Homebrew/resource.rb:88:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/patch.rb:129:in `apply'
/usr/local/Library/Homebrew/extend/leopard.rb:39:in `send'
/usr/local/Library/Homebrew/extend/leopard.rb:39:in `to_proc'
/usr/local/Library/Homebrew/extend/leopard.rb:39:in `each'
/usr/local/Library/Homebrew/formula.rb:852:in `patch'
/usr/local/Library/Homebrew/build.rb:107:in `install'
/usr/local/Library/Homebrew/build.rb:106:in `brew'
/usr/local/Library/Homebrew/formula.rb:859:in `stage'
/usr/local/Library/Homebrew/formula.rb:1405:in `unpack'
/usr/local/Library/Homebrew/resource.rb:88:in `mktemp'
/usr/local/Library/Homebrew/resource.rb:88:in `unpack'
/usr/local/Library/Homebrew/resource.rb:81:in `stage'
/usr/local/Library/Homebrew/formula.rb:1405:in `stage'
/usr/local/Library/Homebrew/formula.rb:859:in `brew'
/usr/local/Library/Homebrew/build.rb:106:in `install'
/usr/local/Library/Homebrew/build.rb:175

**Comment by mistydemeo** [comment]
Should be fixed now; mind running `brew update` and retrying?

**Comment by boudinfl** [comment]
So I had to remove/reinstall tigerbrew because of missing curl/openssl but everything works like a charm now.

Thanks!!
