### ISSUE TITLE
libgphoto2 failed to build on mac OS 10.4

### ISSUE THREAD

**Issue by rghammonds** [mistydemeo/tigerbrew#16]
see https://gist.github.com/rghammonds/5273673 for details

errors:
conftest.c:11:28: error: ac_nonexistent.h: No such file or directory
conftest.c:35:21: error: libintl.h: No such file or directory
conftest.c:45: error: conflicting types for 'libiconv'
conftest.cpp:24:28: error: ac_nonexistent.h: No such file or directory
conftest.c:35:21: error: libintl.h: No such file or directory
conftest.c:36:21: error: libintl.h: No such file or directory
conftest.c:45: error: conflicting types for 'libiconv'
/usr/include/iconv.h:82: error: previous declaration of 'libiconv' was here
conftest.c:43: error: nested functions are disabled, use -fnested-functions to re-enable
conftest.c:44: error: nested functions are disabled, use -fnested-functions to re-enable
conftest.c:47: error: nested functions are disabled, use -fnested-functions to re-enable
conftest.c:80:20: error: mcheck.h: No such file or directory
conftest.c:47:20: error: mcheck.h: No such file or directory
conftest.c:85: error: parse error before ')' token
conftest.c:69:24: error: sys/statfs.h: No such file or directory
conftest.c:70:21: error: sys/vfs.h: No such file or directory
conftest.c:85: error: 'struct statfs' has no member named 'f_favail'
conftest.c:74: error: storage size of 'ac_aggr' isn't known
conftest.c:67:22: error: byteswap.h: No such file or directory
