### ISSUE TITLE
duti doesn't build on Tiger unless I pass --cc=gcc-4.0 on the cmdline

### ISSUE THREAD

**Issue by chdiza** [mistydemeo/tigerbrew#274]
`duti` refuses to build on Tiger PPC, spitting up the following error:

```
/usr/local/bin/gcc-4.2 -isysroot /Developer/SDKs/MacOSX10.4u.sdk -mmacosx-version-min=10.4 -Wall -Wmissing-prototypes -Os -w -pipe -mcpu=7450 -faltivec -mmacosx-version-min=10.4 -c ./util.c
In file included from /Developer/SDKs/MacOSX10.4u.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:12,
                 from ./util.c:1:
/Developer/SDKs/MacOSX10.4u.sdk/usr/include/stdarg.h:4:25: error: stdarg.h: No such file or directory
In file included from /Developer/SDKs/MacOSX10.4u.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16,
                 from ./util.c:1:
/Developer/SDKs/MacOSX10.4u.sdk/usr/include/float.h:8:24: error: float.h: No such file or directory
make: *** [util.o] Error 1
```

Yet I can build it with no problem manually, outside of brew.

Finally I tried `brew install -d --cc=gcc-4.0 duti`, and that worked.  I'd make a PR, but I don't know how to force compilers inside a formula.
