### ISSUE TITLE
Qt failed to build on 10.5

### ISSUE THREAD

**Issue by nino76** [mistydemeo/tigerbrew#92]
I need some help.
Thanks.

patching file src/3rdparty/webkit/Source/WebCore/platform/graphics/mac/MediaPlayerPrivateQTKit.mm
Error: undefined method `>=' for nil:NilClass

http://gist.github.com/nino76/5885220
