### ISSUE TITLE
cairo will not build on Mac OS 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#452]
When building cairo 1.14.2 like this: 'brew -v install cairo', the build fails with this error message:

cairo-quartz-font.c: In function ‘_cairo_quartz_init_glyph_path’:
cairo-quartz-font.c:548: error: ‘CTFontRef’ undeclared (first use in this function)
cairo-quartz-font.c:548: error: (Each undeclared identifier is reported only once
cairo-quartz-font.c:548: error: for each function it appears in.)
cairo-quartz-font.c:548: error: parse error before ‘ctFont’
cairo-quartz-font.c:563: error: ‘ctFont’ undeclared (first use in this function)
cairo-quartz-font.c:563: error: implicit declaration of function ‘CTFontCreateWithGraphicsFont’
cairo-quartz-font.c:564: error: implicit declaration of function ‘CTFontCreatePathForGlyph’
make[3]: *** [Makefile:2342: cairo-quartz-font.lo] Error 1

**Comment by programmingkidx** [comment]
Found out the CTFontRef structure is not defined in Mac OS 10.4. It is new to Mac OS 10.5.

**Comment by mistydemeo** [comment]
This one might be tricky to fix. :/ I'll look into it.

**Comment by programmingkidx** [comment]
https://www.cairographics.org/end_to_end_build_for_mac_os_x/
This page has step by step directions on how to build Cairo for Mac OS 10.4. I successfully did it myself. I could email you the files and you could make a bottled version of Cairo if you want. I used version 1.8.8 of Cairo.

**Comment by programmingkidx** [comment]
Just wanted to report I was able to build Cairo 1.9.4 on Mac OS 10.4. This is the source code I used: http://cairographics.org/snapshots/cairo-1.9.4.tar.gz

**Comment by programmingkidx** [comment]
Had success with building Cairo 1.12.18 on Mac OS 10.4. The directions aren't perfect. I had to download the source code files using a browser, then double click on them to extract all the files. Most the information in the build page was good.

**Comment by programmingkidx** [comment]
Cairo 1.14.8 did not compile. I ran into the CTFontRef error.

**Comment by mistydemeo** [comment]
I wonder how feasible it is to get newer versions working. Maybe we need to pin the formula to an older version. :/

**Comment by programmingkidx** [comment]
On Jan 14, 2017, at 12:56 AM, Misty De Meo wrote:

> I wonder how feasible it is to get newer versions working. Maybe we  
> need to pin the formula to an older version. :/
>

I have successfully made the newest version of Cairo on Mac OS  
10.4 :) All you need to do is apply the two patches I am attaching to  
this email. All you have to do to make Cairo is:
- install and link libpng in brew: brew install libpng && brew link  
libpng
- install and link pixman in brew: brew install pixman && brew link  
pixman
- download and patch cairo 1.14.8 with the patches I am sending you:  
patch -p1 < <path to patch file>
- configure cairo like this: ./configure --disable-xlib --disable-ft  
--disable-dependency-tracking
- 'make'  and 'make install'

You will have a new version of Cairo that works!

Using this tutorial (https://www.cairographics.org/FAQ/ 
#getting_started), I was able to make a program that makes a png file  
with blue text in it that says "hello world".

Did you receive my emails? I'm not sure if I sent them to the right  
email address. I used the email address I found on this page:
https://github.com/mistydemeo. Is this the right email address  
mistydemeo@gmail.com?

**Comment by ranma42** [comment]
I hope to also update the cairo master so that newer versions work fine on 10.4 (I am the maintainer of the Quartz backend; I just recently managed to set up a 10.4 VM so that it should be easier for me to check when issues arise on older versions).

**Comment by mistydemeo** [comment]
That would be great!

> I just recently managed to set up a 10.4 VM

What steps did you use to get it going? Are you using a Hackintosh build? I had some trouble getting 10.4 server in a VM.

**Comment by programmingkidx** [comment]
Did you use VirtualBox? This information may help: https://forums.virtualbox.org/viewtopic.php?f=22&t=80993

**Comment by ranma42** [comment]
@mistydemeo I am running MacOSX 10.4 server on a (modern) MacBook Pro in VirtualBox.
I followed the steps suggested by @programmingkidx (if needed I can provide the vbox XML configuration file and assistance in the process).

**Comment by ranma42** [comment]
I recently updated the patch and posted it (with a proposal to merge it) to the cairo mailing list: https://lists.cairographics.org/archives/cairo/2017-January/027842.html

Notice that I changed the old patch so that `CGFloat` is always defined as `float` if it is not defined on the system. This is because in the 10.4 framework the API always used `float` in the interface. I am unsure how this could seamlessly work when targetting x86-64 with 10.4 as a deployment target and running on 10.5 or newer. Any ideas? (Maybe this problem never occurred in practice as this might be a reasonably narrow use case)
