### ISSUE TITLE
openconnect failed to build on 10.5

### ISSUE THREAD

**Issue by dbdjre0143** [mistydemeo/tigerbrew#584]
Gist: 
https://gist.github.com/dbdjre0143/9e914ad3df69308b77cf9104a63004a8

**Comment by mistydemeo** [comment]
```
auth-juniper.c: In function ‘oncp_https_submit’:
auth-juniper.c:280: error: ‘HTML_PARSE_RECOVER’ undeclared (first use in this function)
auth-juniper.c:280: error: (Each undeclared identifier is reported only once
auth-juniper.c:280: error: for each function it appears in.)
make[1]: *** [libopenconnect_la-auth-juniper.lo] Error 1
make: *** [install-recursive] Error 1
```

Looks like it's trying to use the libxml2 that comes with the OS, but that version is too old. I should be able to fix this, I'll give it a try soon!

**Comment by dbdjre0143** [comment]
Ahh, excellent assumption. I was able to build it by adding libxml2 as a dependency to the openconnect formula. I was going to submit a PR for the change, but I do not have permissions to push my change branch to the repo. I do apologize for the noob question, but I have never contributed to a github project before. Is there anything special I need to do to PR my change?

**Comment by mistydemeo** [comment]
> I do apologize for the noob question, but I have never contributed to a github project before. Is there anything special I need to do to PR my change?

No need to apologize! There's always a first time. :)

You'll need to fork the repository - you can do that by clicking the fork button in the upper right hand corner. You then push the branch to your fork of the repository instead of mine; once you've done that, you should see a notification pop up on the repository with the name of your branch and a button to create a pull request.

The commit naming scheme I use in this repository is to open with the name of the formula, then include a short description of the change. For example, "openconnect: add libxml2 dependency on older OS Xs" or something like that.

**Comment by dbdjre0143** [comment]
So, apologies again, I let this fall by the wayside and forgot about it, until someone was asking about connecting to a Cisco VPN from OSX Leopard and I realized I had never submitted this change. The (one-liner) PR is now up at: https://github.com/mistydemeo/tigerbrew/pull/628

**Comment by mistydemeo** [comment]
Should be fixed now with the most recent version.
