### ISSUE TITLE
wxPython failed to build on 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#619]
When building wxPython on Mac OS 10.4.11 I saw this error message:

./src/osx/utils_osx.cpp:37:40: error: AudioToolbox/AudioServices.h: No such file or directory

**Comment by programmingkidx** [comment]
https://developer.apple.com/library/archive/documentation/MusicAudio/Conceptual/CoreAudioOverview/WhatsinCoreAudio/WhatsinCoreAudio.html
According to this page the functions available in AudioServices.h are available to Mac OS 10.5 and higher.
