### ISSUE TITLE
rtorrent failed to build in 10.4

### ISSUE THREAD

**Issue by buddhajuke** [mistydemeo/tigerbrew#255]
Mon Sep 15 19:10:47 NDT 2014

make

make  all-recursive
Making all in doc
make[2]: Nothing to be done for `all'.
Making all in src
Making all in core
/usr/local/bin/g++-4.9 -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -Os -w -pipe -mcpu=7450 -faltivec -mcpu=7450 -faltivec -mmacosx-version-min=10.4 -DNDEBUG -D_THREAD_SAFE    -I/usr/local/Cellar/libtorrent/0.13.4/include  -c -o curl_get.o curl_get.cc
/usr/local/bin/g++-4.9 -DHAVE_CONFIG_H -I. -I../..  -I. -I./.. -I../..   -Os -w -pipe -mcpu=7450 -faltivec -mcpu=7450 -faltivec -mmacosx-version-min=10.4 -DNDEBUG -D_THREAD_SAFE    -I/usr/local/Cellar/libtorrent/0.13.4/include  -c -o curl_socket.o curl_socket.cc
In file included from curl_socket.cc:48:0:
curl_socket.h:57:56: error: 'curl_socket_t' has not been declared
   static int         receive_socket(void\* easy_handle, curl_socket_t fd, int what, void\* userp, void\* socketp);
                                                        ^
curl_socket.cc:54:47: error: 'curl_socket_t' has not been declared
 CurlSocket::receive_socket(void\* easy_handle, curl_socket_t fd, int what, void\* userp, void\* socketp) {
                                               ^
curl_socket.cc: In static member function 'static int core::CurlSocket::receive_socket(void_, int, int, void_, void_)':
curl_socket.cc:58:15: error: 'CURL_POLL_REMOVE' was not declared in this scope
   if (what == CURL_POLL_REMOVE) {
               ^
curl_socket.cc:80:15: error: 'CURL_POLL_NONE' was not declared in this scope
   if (what == CURL_POLL_NONE || what == CURL_POLL_OUT)
               ^
curl_socket.cc:80:41: error: 'CURL_POLL_OUT' was not declared in this scope
   if (what == CURL_POLL_NONE || what == CURL_POLL_OUT)
                                         ^
curl_socket.cc:85:15: error: 'CURL_POLL_NONE' was not declared in this scope
   if (what == CURL_POLL_NONE || what == CURL_POLL_IN)
               ^
curl_socket.cc:85:41: error: 'CURL_POLL_IN' was not declared in this scope
   if (what == CURL_POLL_NONE || what == CURL_POLL_IN)
                                         ^
make[3]: *_\* [curl_socket.o] Error 1
make[2]: **\* [all-recursive] Error 1
make[1]: **\* [all-recursive] Error 1
make: **\* [all] Error 2

HOMEBREW_VERSION: 0.9.5
HEAD: e564fd7c14d575ed4b2a4f8c2842c40d6a018c8f
CPU: single-core 32-bit g4e
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
X11: 1.1.3 => /usr/X11R6

**Comment by e-inquirer** [comment]
Tried both standard install and gcc-4.2 build.
____
Standard:
````
$ brew install rtorrent
==> Installing dependencies for rtorrent: libtorrent
==> Installing rtorrent dependency: libtorrent
Error: libtorrent cannot be built with any available compilers.
To install this formula, you may need to either:
  brew install apple-gcc42
or:
  brew install gcc
```
gcc-4.2
````
$ brew install rtorrent --cc=gcc-4.2
==> Installing dependencies for rtorrent: libtorrent
==> Installing rtorrent dependency: libtorrent
==> Downloading http://rtorrent.net/downloads/libtorrent-0.13.6.tar.gz
######################################################################## 100.0%
==> Downloading https://trac.macports.org/export/124274/trunk/dports/net/libtorr
######################################################################## 100.0%
==> Patching
==> Applying no_posix_memalign.patch
patching file rak/allocators.h
==> sh autogen.sh
==> ./configure --prefix=/usr/local/Cellar/libtorrent/0.13.6 --with-kqueue --ena
==> make
Last 15 lines from /Users/workstation/Library/Logs/Homebrew/libtorrent/03.make:
/usr/include/c++/4.0.0/bits/vector.tcc:275:   instantiated from ‘void std::vector<_Tp, _Alloc>::_M_insert_aux(__gnu_cxx::__normal_iterator<typename _Alloc::pointer, std::vector<_Tp, _Alloc> >, const _Tp&) [with _Tp = unsigned int, _Alloc = rak::cacheline_allocator<void*>]’
/usr/include/c++/4.0.0/bits/stl_vector.h:610:   instantiated from ‘void std::vector<_Tp, _Alloc>::push_back(const _Tp&) [with _Tp = unsigned int, _Alloc = rak::cacheline_allocator<void*>]’
./../net/socket_set.h:135:   instantiated from here
/usr/include/c++/4.0.0/bits/stl_vector.h:117: error: cannot convert ‘void**’ to ‘unsigned int*’ in return
/usr/include/c++/4.0.0/bits/stl_vector.h: In member function ‘void std::_Vector_base<_Tp, _Alloc>::_M_deallocate(_Tp*, size_t) [with _Tp = unsigned int, _Alloc = rak::cacheline_allocator<void*>]’:
/usr/include/c++/4.0.0/bits/vector.tcc:295:   instantiated from ‘void std::vector<_Tp, _Alloc>::_M_insert_aux(__gnu_cxx::__normal_iterator<typename _Alloc::pointer, std::vector<_Tp, _Alloc> >, const _Tp&) [with _Tp = unsigned int, _Alloc = rak::cacheline_allocator<void*>]’
/usr/include/c++/4.0.0/bits/stl_vector.h:610:   instantiated from ‘void std::vector<_Tp, _Alloc>::push_back(const _Tp&) [with _Tp = unsigned int, _Alloc = rak::cacheline_allocator<void*>]’
./../net/socket_set.h:135:   instantiated from here
/usr/include/c++/4.0.0/bits/stl_vector.h:123: error: no matching function for call to ‘std::_Vector_base<unsigned int, rak::cacheline_allocator<void*> >::_Vector_impl::deallocate(unsigned int*&, size_t&)’
../../rak/allocators.h:90: note: candidates are: void rak::cacheline_allocator<T>::deallocate(T*, size_t) [with T = void*]
make[4]: *** [poll_select.lo] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Error: No such file or directory - /usr/sbin/pkgutil

````
____
The config info:
````
$ brew --config
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: 1cdf87c6f13ae0738e5ba0ca31248d2e7efa0bd5
Last commit: 4 months ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://ia902307.us.archive.org/31/items/tigerbrew
CPU: single-core 32-bit g4e
OS X: 10.4.11-Power Macintosh
Xcode: 2.5
CLT: N/A
GCC-4.0: build 5370
GCC-4.2: build 5553
Clang: N/A
X11: N/A
System Ruby: 1.8.2 => /usr/bin/ruby
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
Ruby: /usr/bin/ruby => /Users/workstation
Java: N/A
````
____
Is the problem the makefile, my GCC, or something else? Any solutions?

Thanks in advance.
____
Related: #237
