### ISSUE TITLE
lsof 4.89 does not build - "FATAL: can't find libproc.h" (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#426]
Build dies early in the configure process after applying the patch. Console output:

https://gist.github.com/dcwar/c08141675afd23da083f4a0e402e78e6

**Comment by mistydemeo** [comment]
Hm, I think libproc should be available. Do you have a file at `/usr/include/libproc.h`?

**Comment by dcwar** [comment]
Just checked - that file isn't available at that location on the system.

**Comment by ranma42** [comment]
Apparently Tiger ships `libproc.dylib`, but not its header.

**Comment by mistydemeo** [comment]
I'll dig up the source from opensource.apple.com and create a header package.

**Comment by mistydemeo** [comment]
Checking Tiger's sources, libproc existed as a set of private functions in the kernel; there weren't any headers, even internal to xnu itself. The headers first appeared in Leopard's libc. I'll write a header for Tiger based on what's defined in the xnu source.

**Comment by mistydemeo** [comment]
Did some digging, but it looks like the function signatures have changed between the private versions in xnu in 10.4 and the public versions in libc in 10.5 and later. lsof isn't compatible with Tiger's version.

**Comment by ranma42** [comment]
It is normal that the signatures of the kernel syscalls and those of the libproc functions are different. The same holds true for later versions (the kernel functions require an additional `retval` argument).

I made a PR to your libproc repository that fixes the build of your `lsof_fix_tiger` branch  :)

**Comment by mistydemeo** [comment]
Confirmed working on 10.4.11 Intel with the custom headers; I need to test on PowerPC, but won't be able to do that for about two weeks.

**Comment by dcwar** [comment]
I'm sorry to say that the PPC build fails. Console output: https://gist.github.com/dcwar/aeb49c6729a68922a777c6da19aed852

**Comment by mistydemeo** [comment]
Hmmm. 

```
cc -o lsof  -DHASIPv6 -mdynamic-no-pic -DHASUTMPX -DDARWINV=800 -DHAS_STRFTIME -DLSOF_VSTR=\"8.11.0\" -I/usr/include -I/private/tmp/lsof20170428-7649-vlctwz/lsof_4.89/lsof_4.89_src/include -O ddev.o dfile.o dmnt.o dproc.o dsock.o dstore.o arg.o main.o misc.o node.o print.o proc.o store.o usage.o util.o -L./lib -llsof  -lcurses -lproc
/usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/ld: can't locate file for: -lproc
```

That suggests that `libproc` isn't shipped on 10.4.11-ppc. Is there a `/usr/lib/libproc.dylib`?

**Comment by dcwar** [comment]
I'm afraid `/usr/lib/libproc.dylib` isn't present on my ppc system.

**Comment by ranma42** [comment]
Weird, on i386 10.4 there is a universal (i386/ppc) libproc.dylib.

**Comment by dcwar** [comment]
I know it's been forever since this thread was active, but would it be possible to vendor a copy of that dylib? Or perhaps you can send it to me for testing purposes? :)

It's weird that my system has a stock Xcode install and is missing that.

**Comment by mistydemeo** [comment]
I should have taken some notes on this, but if I remember right I tried digging up the userland libproc and had a bit of trouble finding it at opensource.apple.com. That said, I'd like to ship it in Tigerbrew if we succeed in locating it; it'd obviously be a big help.

This isn't the first time I've seen 10.4 Intel ship something that's missing from the PPC variant.

**Comment by ranma42** [comment]
This is the oldest version I could find of the libproc source code:
https://opensource.apple.com/source/Libc/Libc-498/darwin/libproc.c

**Comment by cellularmitosis** [comment]
Reviving this thread years later, as I've also been hit by "can't find libproc.h" while trying to build GNU gettext from source.

I'm on PowerPC Tiger, and as mentioned above, just installing the headers isn't sufficient because I don't have a libproc.dylib.

Here is my attempt at back-porting a libproc using the Libc and xnu sources from Leopard:

```sh
#!/bin/bash

# my attempt at backporting a libproc.dylib from leopard to tiger.

# see the tigerbrew thread at https://github.com/mistydemeo/tigerbrew/issues/426

set -e -x

osversion=$(sw_vers -productVersion | awk '{print $NF}')
if ! echo $osversion | grep -q '10\.4' ; then
    echo "Error: run this script on a Mac running Tiger." >&2
    exit 1
fi

mkdir -p ~/Downloads
cd ~/Downloads
if ! test -e xnu-1228.15.4.tar.gz ; then
    curl -LO https://github.com/apple-oss-distributions/xnu/archive/xnu-1228.15.4.tar.gz
fi
if ! test -e Libc-498.1.7.tar.gz ; then
    curl -LO https://github.com/apple-oss-distributions/Libc/archive/Libc-498.1.7.tar.gz
fi

rm -rf /tmp/libproc
mkdir /tmp/libproc
cd /tmp/libproc

tar xzf ~/Downloads/Libc-Libc-498.1.7.tar.gz
tar xzf ~/Downloads/xnu-xnu-1228.15.4.tar.gz

cd Libc-Libc-498.1.7/darwin
mkdir sys
cp /tmp/libproc/xnu-xnu-1228.15.4/bsd/sys/proc_info.h sys/

gcc -I . -c libproc.c

# Note: '$ gcc -dynamiclib libproc.o -o libproc.dylib' fails with:
# ld: Undefined symbols:
# ___proc_info
# /usr/libexec/gcc/powerpc-apple-darwin8/4.0.1/libtool: internal link edit command failed

# It appears this is a system kernel symbol from Libsystem,
# see https://github.com/NixOS/nixpkgs/blob/master/pkgs/os-specific/darwin/apple-source-releases/Libsystem/system_kernel_symbols

# However, adding '-lSystem' does not help.

# We can force it, thanks to https://stackoverflow.com/a/3532716
gcc -dynamiclib -undefined suppress -flat_namespace libproc.o -o libproc.dylib

# This will allow test.c to build, but will fail at run-time with:
# dyld: lazy symbol binding failed: Symbol not found: ___proc_info
#   Referenced from: /usr/lib/libproc.dylib
#   Expected in: flat namespace
# dyld: Symbol not found: ___proc_info
#   Referenced from: /usr/lib/libproc.dylib
#   Expected in: flat namespace

mkdir -p /tmp/libproc/usr/lib /tmp/libproc/usr/include/sys
cp libproc.dylib /tmp/libproc/usr/lib/
cp libproc.h /tmp/libproc/usr/include/
cp sys/proc_info.h /tmp/libproc/usr/include/sys/

cd /tmp/libproc
tar czf /tmp/libproc.tar.gz usr

# Here is a bit of test code.
# Thanks to https://stackoverflow.com/questions/37512486/osx-proc-pidinfo-returns-0-for-other-users-processes
cat > /tmp/test.c << "EOF"
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

#include <libproc.h>

int main(int argc, char *argv[])
{
    pid_t pid;
    struct proc_bsdinfo proc;

    if (argc == 2)
        pid = atoi(argv[1]);
    else
        pid = getpid();

    int st = proc_pidinfo(pid, PROC_PIDTBSDINFO, 0,
                         &proc, PROC_PIDTBSDINFO_SIZE);

    if (st != PROC_PIDTBSDINFO_SIZE) {
        fprintf(stderr, "Cannot get process info");
        return 1;
    }
    printf(" pid: %d\n", (int)proc.pbi_pid);
    printf("ppid: %d\n", (int)proc.pbi_ppid);
    printf("comm: %s\n",      proc.pbi_comm);
    printf("name: %s\n",      proc.pbi_name);
    printf(" uid: %d\n", (int)proc.pbi_uid);
    printf(" gid: %d\n", (int)proc.pbi_gid);

    return 0;
}
EOF

set +x
echo
echo "To install, run:"
echo "cd / && sudo tar xzvf /tmp/libproc.tar.gz"
echo
echo "To test, run:"
echo "cd /tmp && gcc -lproc test.c && ./a.out"
```

However, the test still fails:

```
$ cd /tmp && gcc -lproc test.c && ./a.out
dyld: lazy symbol binding failed: Symbol not found: ___proc_info
  Referenced from: /usr/lib/libproc.dylib
  Expected in: flat namespace

dyld: Symbol not found: ___proc_info
  Referenced from: /usr/lib/libproc.dylib
  Expected in: flat namespace

Trace/BPT trap
```

I'll admit that I don't know what I'm doing when it comes to "linking against the kernel", or however it is that one is supposed to access things like `___proc_info`.

Any tips on `___proc_info` would be greatly appreciated!  Thanks for keeping these old PowerPC machines alive :)

**Comment by barracuda156** [comment]
@cellularmitosis This is a related topic here: https://trac.macports.org/ticket/58160

**Comment by cellularmitosis** [comment]
> [@cellularmitosis](https://github.com/cellularmitosis) This is a related topic here: https://trac.macports.org/ticket/58160

Thanks so much for pointing this out!  I’ve been curious about building my own XNU kernel.

**Comment by barracuda156** [comment]
@cellularmitosis BTW, provisionally it could be more or less trivial via `darwinbuild` (it used to work on 10.4, at least). MacPorts version has defunct URLs (so it will not work as-is), but you look at patches here https://github.com/macos-powerpc/darwinbuild and do something similar to the older version, or possibly build 10.4 stuff from 10.6.
Remind me later, I think I have fetched “roots” for darwin8, it should be easier to start from having those compiled.

**Comment by cellularmitosis** [comment]
> [@cellularmitosis](https://github.com/cellularmitosis) BTW, provisionally it could be more or less trivial via `darwinbuild` (it used to work on 10.4, at least). MacPorts version has defunct URLs (so it will not work as-is), but you could look at patches here https://github.com/macos-powerpc/darwinbuild and do something similar to the older version, or possibly build 10.4 stuff from 10.6. Remind me later, I think I have fetched “roots” for darwin8, it should be easier to start from having those compiled.

Amazing!
