### ISSUE TITLE
homebrew/dupes/nano (2.4.2_1) build fails (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#348]
Build fails during the compile, starting on line 83 of the make log:

nano.c: In function 'signal_init':
nano.c:1240: error: 'SIGWINCH' undeclared (first use in this function)
nano.c:1240: error: (Each undeclared identifier is reported only once
nano.c:1240: error: for each function it appears in.)
nano.c: In function 'allow_pending_sigwinch':
nano.c:1405: error: 'SIGWINCH' undeclared (first use in this function)

Not entirely sure of the best way to solve this issue… although I can say that this did not occur in the previous versions in Tigerbrew. 

01.Configure --> https://gist.github.com/dcwar/a2a3ef1e81d1865b2a76
02.Make --> https://gist.github.com/dcwar/58ac66928e51cbe29442
03.Config.log --> https://gist.github.com/dcwar/ae3aeb24241c28c7115c

**Comment by mistydemeo** [comment]
I can repro. Works on 10.5, not 10.4.

Both 10.4 and 10.5 define `SIGWINCH`, but they guard the definitions differently.

10.4:
```c
#if  !defined(_POSIX_C_SOURCE)
#define SIGWINCH 28 /* window size changes */
#define SIGINFO 29  /* information request */
#endif
```

10.5:
```c
#if  (!defined(_POSIX_C_SOURCE) || defined(_DARWIN_C_SOURCE))
#define SIGWINCH 28 /* window size changes */
#define SIGINFO 29  /* information request */
#endif
```

**Comment by mistydemeo** [comment]
Found it - nano defines `_XOPEN_SOURCE`, which causes `_POSIX_C_SOURCE` to be defined. `SIGWINCH` is still defined on newer OS Xs, but in Tiger it means it won't be defined. Fixed by undefining that constant on 10.4 only.

**Comment by mistydemeo** [comment]
Aha, and the reason this didn't come up before: `ncurses6-config` defines `-D_XOPEN_SOURCE=500` on 10.4, which ncurses 5 didn't.

**Comment by dcwar** [comment]
Ahhhhh! Okay, that explains a lot. Thank you so much!
