### ISSUE TITLE
uwsgi failed to build on 10.4.11 [Intel Tiger]

### ISSUE THREAD

**Issue by florent-f** [mistydemeo/tigerbrew#98]
Hi,

uwsgi installation fails with the following error message:
core/emperor.c: In function 'uwsgi_emperor_vassal_start':
core/emperor.c:870: error: void value not ignored as it ought to be
Error: uwsgi did not build

It fails without writing any file in the log directory:
~/Library/Logs/Homebrew/uwsgi/

Here's the github file:
https://gist.github.com/florent-f/7bcde3e9a3cdc2e3ee86

Any idea ?
Thanks
