### ISSUE TITLE
Perl failed to install on Mac OS 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#1500]
Saw this error while building perl 5.42.0 on Mac OS 10.4.11:

```
In file included from sv.c:32:
sv.c: In function 'Perl_more_bodies':
perl.h:5324:48: error: implicit declaration of function 'malloc_good_size'; did you mean 'malloc_size'? [-Wimplicit-function-declaration]
 5324 | #       define Perl_malloc_good_size(how_much) malloc_good_size(how_much)
      |                                                ^~~~~~~~~~~~~~~~
sv.c:868:36: note: in expansion of macro 'Perl_malloc_good_size'
  868 |     const size_t good_arena_size = Perl_malloc_good_size(arena_size);
      |                                    ^~~~~~~~~~~~~~~~~~~~~
sv.c: In function 'Perl_sv_vcatpvfn_flags':
sv.c:13089:21: error: expected identifier or '(' before ':' token
13089 |               vector:
      |                     ^
sv.c:13896:18: error: expected identifier or '*' before '__attribute__'
13896 |             goto vector; /* do next iteration */
      |                  ^~~~~~
```

https://gist.github.com/programmingkidx/7e86e177ac1864d31df7783d3c7745c8

**Comment by mistydemeo** [comment]
Hm, `configure` seems to think it found `malloc_good_size`. Did it miss the right include for this OS version? https://gist.github.com/programmingkidx/7e86e177ac1864d31df7783d3c7745c8#file-gistfile1-txt-L514

**Comment by programmingkidx** [comment]
According to "man malloc_good_size" this function is found in stdlib.h.

**Comment by mistydemeo** [comment]
Hm, looks like `perl.h` (included by `sv.c`) does `#include <stdlib.h>`. That should have been sufficient.

**Comment by programmingkidx** [comment]
Does perl 5.42 build on your computer running Mac OS 10.4?

**Comment by programmingkidx** [comment]
The code where the "#include <stdlib.h>" in perl.h does run. I placed an "#error" right below to verify this. 

To note I building outside of tigerbrew using this command: ./configure -d && make

**Comment by programmingkidx** [comment]
The end result was the same error message for malloc_good_size() when using "./configure -d && make".

**Comment by programmingkidx** [comment]
This program tries to use malloc_good_size():

```
#include <stdio.h>
#include <stdlib.h>
#include <malloc/malloc.h>

int main(void) {
    size_t requested = 50;
    size_t actual = malloc_good_size(requested);

    printf("Requested size: %zu bytes\n", requested);
    printf("malloc_good_size(): %zu bytes\n", actual);

    void *p = malloc(requested);
    if (p == NULL) {
        perror("malloc");
        return 1;
    }

    printf("malloc() returned a block of %zu bytes\n", malloc_size(p));

    free(p);
    return 0;
}

```

On Mac OS 10.4
- gcc-3.3: works
- gcc-4.0: works
- gcc 14.2.0: fails to compile because malloc_good_size() can't be found.
-

**Comment by mistydemeo** [comment]
Oh! Well then, it being a GCC 14.2.0 issue is very interesting information.

**Comment by programmingkidx** [comment]
I would have thought the results would have been the other way around.

**Comment by programmingkidx** [comment]
I tried building again using gcc-4.0, and it still fails to find malloc_good_size(). 

Command used: CC=gcc-4.0 CXX=g++-4.0 VERBOSE=1 brew install perl

**Comment by mistydemeo** [comment]
To tell Homebrew what compiler to use, you'll need to use a commandline flag rather than envionment variables - `brew install perl --cc=gcc-4.0`

**Comment by programmingkidx** [comment]
I tried building again using this command: 
VERBOSE=1 brew install perl --cc=gcc-4.0 --cxx=g++-4.0

The result was I still saw the error message about missing malloc_good_size().

**Comment by mistydemeo** [comment]
Can I see the logs from that attempt?

**Comment by programmingkidx** [comment]
Sure

[01.Configure.txt](https://github.com/user-attachments/files/25300598/01.Configure.txt)
[02.make.txt](https://github.com/user-attachments/files/25300597/02.make.txt)

**Comment by sevan** [comment]
hmm, for sure Perl 5.42 built with GCC 4.0 on Tiger for me.
Does it help if you drop `/opt/gcc14/bin` from `$PATH`?

Also, what does the output of `cc -v` say?

**Comment by sevan** [comment]
New release of Perl landed, can you try with GCC 14 on the new release and see if it progresses further?

**Comment by coffnix** [comment]
try my solution here: https://github.com/mistydemeo/tigerbrew/issues/1551

**Comment by sevan** [comment]
> try my solution here: [#1551](https://github.com/mistydemeo/tigerbrew/issues/1551)

Different problem. This is specific to building with GCC 14 as the op has reported it works with [GCC 3.x / 4.x](https://github.com/mistydemeo/tigerbrew/issues/1500#issuecomment-3898839230)

**Comment by coffnix** [comment]
> > try my solution here: [#1551](https://github.com/mistydemeo/tigerbrew/issues/1551)
> 
> Different problem. This is specific to building with GCC 14 as the op has reported it works with [GCC 3.x / 4.x](https://github.com/mistydemeo/tigerbrew/issues/1500#issuecomment-3898839230)

I’m testing it with GCC 4.0 and 4.2, and later I’ll test it with GCC 14. I recommend GCC 13 anyway. Even on my Linux systems I usually use GCC 13 because GCC 14 introduced major changes related to C99.

**Comment by sevan** [comment]
@programmingkidx to paper over the issue you can pass `-Dd_malloc_good_size='undef'` to Perl's `Configure` script, just to sidestep the issue and get it built with GCC 14.
I'm looking into why GCC 14 is not finding the symbol. It's there in libSystem but not sure why it's not happy about it.
With the workaround, the `perl` binary built with GCC 14 has linked to libsystem, so not sure what's going on yet.

**Comment by sevan** [comment]
Ok. The `malloc_good_size` symbol is there in `libSystem`, and it's all documented in `malloc(3)` but it's not defined in any headers.
So the test program provided here fails when built with GCC 14 and Perl's configure process picks up the symbol from libc aka libSystem.
Building the [test program here](https://github.com/mistydemeo/tigerbrew/issues/1500#issuecomment-3898839230) with `-Wno-implicit-function-declaration` works and I see 
```
Requested size: 50 bytes
malloc_good_size(): 64 bytes
malloc() returned a block of 64 bytes
```
On my iMac G5 running 10.4.11.

**Comment by sevan** [comment]
With GCC 4.0.1, it'll warn about implicit declaration of functions and continue on if you turn warnings on. I guess they were turned into hard errors at some point (GCC 14?)
