### PR TITLE
cairo: fix build on 10.4

### LINKED ISSUE #452: cairo will not build on Mac OS 10.4
When building cairo 1.14.2 like this: 'brew -v install cairo', the build fails with this error message:

cairo-quartz-font.c: In function ‘_cairo_quartz_init_glyph_path’:
cairo-quartz-font.c:548: error: ‘CTFontRef’ undeclared (first use in this function)
cairo-quartz-font.c:548: error: (Each undeclared identifier is reported only once
cairo-quartz-font.c:548: error: for each function it appears in.)
cairo-quartz-font.c:548: error: parse error before ‘ctFont’
cairo-quartz-font.c:563: error: ‘ctFont’ undeclared (first use in this function)
cairo-quartz-font.c:563: error: implicit declaration of function ‘CTFontCreateWithGraphicsFont’
cairo-quartz-font.c:564: error: implicit declaration of function ‘CTFontCreatePathForGlyph’
make[3]: *** [Makefile:2342: cairo-quartz-font.lo] Error 1

### PR DESCRIPTION
**Pull request by mistydemeo**
Also updates to the latest version.

Fixes #452.

cc @ranma42 - mind testing this?

### CODE REVIEW

**Comment by ranma42** [comment]
`brew install cairo` in my environment fails because glib seems to require a newer python (this [gist](https://gist.github.com/ranma42/c2bc7a648f47fd6fe32fc5cff0eaabf3) shows my env and the error).

`brew install python` seems to fix the installation of the glib dependency, which then makes cairo install just fine as shown [here](https://gist.github.com/ranma42/7a073e847cceb99af7c87da9c18e27ba)

**Comment by ranma42** [comment]
The `configure.ac` file for glib seems to indicate that it requires [python 2.5 or newer](https://github.com/GNOME/glib/blob/40cf271a779ed2bb29361b6e9fb6b9f814204d47/configure.ac#L395). MacOSX 10.4 (even if you install XCode 2.5) ships with python 2.3.5, so maybe the right fix is to add `python` as a dependency for `glib` (tigerbrew already handles glib on 10.4 in a special way because of the outdated zlib).

**Comment by mistydemeo** [comment]
Added the Python dep.
