### ISSUE TITLE
Qt failed to build on 10.5.8 (Leopard): error: ‘kCFURLIsHiddenKey’ was not declared in this scope

### ISSUE THREAD

**Issue by uwehermann** [mistydemeo/tigerbrew#303]
```
gcc-4.2 -c -pipe -O2 -arch ppc -arch ppc -Xarch_ppc -mmacosx-version-min=10.4 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -DQT_SHARED -DQT_BUILD_GUI_LIB -DQT_NO_USING_NAMESPACE -DQT_NO_CAST_TO_ASCII -DQT_ASCII_CAST_WARNINGS -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_USE_BUNDLED_LIBPNG -DPNG_NO_ASSEMBLER_CODE -DQT_NO_CUPS -DQT_NO_LPR -DQT_NO_OPENTYPE -DQT_NO_STYLE_WINDOWSVISTA -DQT_NO_STYLE_WINDOWSXP -DQT_NO_STYLE_GTK -DQT_NO_STYLE_WINDOWSCE -DQT_NO_STYLE_WINDOWSMOBILE -DQT_NO_STYLE_S60 -DQ_INTERNAL_QAPP_SRC -DQT_NO_DEBUG -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../mkspecs/macx-g++ -I. -I../../include/QtCore -I../../include -I../../include/QtGui -I.rcc/release-shared -Iimage -I../3rdparty/libpng -I../3rdparty/harfbuzz/src -Idialogs -I.moc/release-shared -I.uic/release-shared -F/private/tmp/qt-BPxlsD/qt-everywhere-opensource-src-4.8.6/lib dialogs/qfiledialog_mac.mm -o .obj/release-shared/qfiledialog_mac.o
dialogs/qfiledialog_mac.mm: In function ‘BOOL -[QNSOpenSavePanelDelegate isHiddenFile:isDir:](QNSOpenSavePanelDelegate*, objc_selector*, NSString*, BOOL)’:
dialogs/qfiledialog_mac.mm:300: error: ‘kCFURLIsHiddenKey’ was not declared in this scope
dialogs/qfiledialog_mac.mm:300: error: ‘CFURLCopyResourcePropertyForKey’ was not declared in this scope
make[2]: *** [.obj/release-shared/qfiledialog_mac.o] Error 1
make[1]: *** [release] Error 2
make: *** [sub-gui-make_default-ordered] Error 2
==> Configuration
HOMEBREW_VERSION: 0.9.5
ORIGIN: https://github.com/mistydemeo/tigerbrew.git
HEAD: caa293144a2d827551aec5695f6d25f4ecd4bbb4
Last commit: 4 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CELLAR: /usr/local/Cellar
CPU: single-core 32-bit g4e
OS X: 10.5.8-Power Macintosh
Xcode: 3.1.4
CLT: N/A
GCC-4.0: build 5493
GCC-4.2: build 5577
LLVM-GCC: build 2064
Clang: N/A
X11: 2.1.6 => /usr/X11
System Ruby: 1.8.6-369
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/bin/ruby
Java: N/A
==> ENV
HOMEBREW_CC: gcc-4.2
HOMEBREW_CXX: g++-4.2
MAKEFLAGS: -j1
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Library/ENV/pkgconfig/10.5
HOMEBREW_MAKE_JOBS: 1
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Library/ENV/3.1.4:/usr/bin:/bin:/usr/sbin:/sbin

Error: qt 4.8.6 did not build
```

```
PowerBook-G4:~ user$ brew doctor
Your system is ready to brew.
```

**Comment by mistydemeo** [comment]
Looks like this needs a patch: https://trac.macports.org/ticket/43746

**Comment by ivanholmes** [comment]
I've submitted a patch for this, which allowed me to successfully compile on Leopard.
