### ISSUE TITLE
gstreamer fails to build on pbg4 17" running OS 10.4.9

### ISSUE THREAD

**Issue by emninger** [mistydemeo/tigerbrew#368]
It's basically the same error i encountered when trying to install htop:

----

:~$ brew install gstreamer
==> Downloading https://download.gnome.org/sources/gstreamer/1.6/gstreamer-1.6.0
Already downloaded: /Library/Caches/Homebrew/gstreamer-1.6.0.tar.xz
==> ./configure --prefix=/usr/local/Cellar/gstreamer/1.6.0 --disable-gtk-doc --e
==> make
Last 15 lines from /Users/parndt/Library/Logs/Homebrew/gstreamer/02.make:
  CC       gst_ptp_helper-gst-ptp-helper.o
In file included from gst-ptp-helper.c:40:
/usr/include/net/if.h:213: error: field 'ifru_addr' has incomplete type
/usr/include/net/if.h:214: error: field 'ifru_dstaddr' has incomplete type
/usr/include/net/if.h:215: error: field 'ifru_broadaddr' has incomplete type
/usr/include/net/if.h:250: error: field 'ifra_addr' has incomplete type
/usr/include/net/if.h:251: error: field 'ifra_broadaddr' has incomplete type
/usr/include/net/if.h:252: error: field 'ifra_mask' has incomplete type
/usr/include/net/if.h:318: error: field 'addr' has incomplete type
/usr/include/net/if.h:319: error: field 'dstaddr' has incomplete type
make[4]: *** [gst_ptp_helper-gst-ptp-helper.o] Error 1
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
Error: Permission denied - /usr/libexec/java_home
-----

**Comment by mistydemeo** [comment]
This looks like a different error. Do you mind uploading the logs from `~/Library/Logs/Homebrew/gstreamer`?

**Comment by emninger** [comment]
How? There are 3 relatively big files. Certainly i cannot post them here as content. Is there a way to upload files?

**Comment by mistydemeo** [comment]
You can upload their contents to gist.github.com and paste the link here!

**Comment by emninger** [comment]
https://gist.github.com/emninger/567b460b257948816be5#file-01configure
https://gist.github.com/emninger/567b460b257948816be5#file-02-make
https://gist.github.com/emninger/567b460b257948816be5#file-config-log

**Comment by mistydemeo** [comment]
Does seem to be the header issue from above:

```
In file included from gst-ptp-helper.c:40:
/usr/include/net/if.h:213: error: field 'ifru_addr' has incomplete type
/usr/include/net/if.h:214: error: field 'ifru_dstaddr' has incomplete type
/usr/include/net/if.h:215: error: field 'ifru_broadaddr' has incomplete type
/usr/include/net/if.h:250: error: field 'ifra_addr' has incomplete type
/usr/include/net/if.h:251: error: field 'ifra_broadaddr' has incomplete type
/usr/include/net/if.h:252: error: field 'ifra_mask' has incomplete type
/usr/include/net/if.h:318: error: field 'addr' has incomplete type
/usr/include/net/if.h:319: error: field 'dstaddr' has incomplete type
```

**Comment by emninger** [comment]
And what does that mean for a common mortal? Like me ...
