### ISSUE TITLE
wxwidgets will not build on Mac OS 10.4

### ISSUE THREAD

**Issue by programmingkidx** [mistydemeo/tigerbrew#459]
brew install wxwidgets
After issuing the command above I saw this error message:

./src/osx/utils_osx.cpp:37:40: error: AudioToolbox/AudioServices.h: No such file or directory
make: *** [Makefile:32015: coredll_utils_osx.o] Error 1
