### PR TITLE
Patch fixes ‘kCFURLIsHiddenKey’ was not declared in this scope on leopar...

### PR DESCRIPTION
**Pull request by ivanholmes**
Will fix this issue: https://github.com/mistydemeo/tigerbrew/issues/303

Sorry if I've done this wrong; I have no idea how to use git or github.

### CODE REVIEW

**Comment by mistydemeo** [comment]
Thank you! I've merged the libtorrent-rasterbar patches as 604bb9585562b814c5bcef94446e80bc613a43f9 and d1e9feba8fac5b2386bb836bcd1ba9d0a83815c6. I'll test the Qt fixes and merge those afterwards.

**Comment by mistydemeo** [comment]
This took a little adaptation to get working with 4.8.7, but it worked - thank you! Currently building binary packages, then I'll merge the patch.

**Comment by mistydemeo** [comment]
Thank you!
