### ISSUE TITLE
cmake 3.2.1 will not build (10.4/G4)

### ISSUE THREAD

**Issue by dcwar** [mistydemeo/tigerbrew#320]
Cmake 3.2.1 will not build with either gcc 4.2 or gcc 4.9. While gcc 4.2 fails fairly quickly with an error relating to 10.4 SDK files, 4.9 gets 85% through the make before failing. Make and bootstrap files are included below.

Interesting notes: without specifying a compiler, cmake seems to build with gcc 4.9 by default - I had to manually specify building with gcc 4.2. For both compilers, toward the end of the bootstrap, both produce the note "You must: brew install svn." [Trying to install svn produces "Error: No available formula for apr (dependency of subversion)... Please tap it and try again...." Since it's already tapped, this whole effort goes nowhere lol.]

gcc 4.2 - 06.bootstrap
https://gist.github.com/dcwar/2c9176ba18736e9febdf
gcc 4.2 - 07.make
https://gist.github.com/dcwar/f11dea5c015b54e908a3
gcc 4.9 - 06.bootstrap
https://gist.github.com/dcwar/cd710e42aa8ed66e61e7
gcc 4.9 - 07.make
https://gist.github.com/dcwar/a89934d7d6c3c73cbe95

Please let me know if there is anything else you might need to help diagnose. I have the complete log files for both attempts.

**Comment by mistydemeo** [comment]
```
/tmp/cmake20150421-13106-o2mtrp/cmake-3.2.1/Source/CTest/cmCTestCurl.cxx: In member function 'std::string cmCTestCurl::Escape(const string&)':
/tmp/cmake20150421-13106-o2mtrp/cmake-3.2.1/Source/CTest/cmCTestCurl.cxx:39:63: error: 'curl_easy_escape' was not declared in this scope
   char* data1 = curl_easy_escape(this->Curl, source.c_str(), 0);
                                                               ^
```

Hm, looks like it needs a newer curl than Tiger includes.

(The reason it goes straight to gcc-4.9 is because the formula's marked as incompatible - you can force it to try anyway, but the compiler selection won't pick it on its own.)

**Comment by chdiza** [comment]
This is the reason for #319.

**Comment by dcwar** [comment]
Thanks @chdiza and @mistydemeo. #319 was the solution.
