### ISSUE TITLE
openal-soft failed to build on 10.5 Intel

### ISSUE THREAD

**Issue by alexey-lysiuk** [mistydemeo/tigerbrew#336]
Compilation error, some kind of static assert, prevents installation of OpenAL
Logs are here: https://gist.github.com/alexey-lysiuk/37e94f90ffe5a18a7a23

**Comment by alexey-lysiuk** [comment]
openal-soft 1.15 was built without a problem.

**Comment by mistydemeo** [comment]
Should be fixed now. Sorry for the delay!
